#!/usr/bin/env python3
"""Prepare NuScenes data for DriveStudio (OmniRe) training.

DriveStudio's NuScenes dataloader expects data in a specific directory layout.
This script verifies the NuScenes mini structure and creates a DriveStudio-compatible
symlink/config pointing at the existing data.

Usage:
    python scripts/prepare_nuscenes_for_drivestudio.py \
        --nuscenes-root /home/luosx/3dgs/data/nuscenes2mcap/data \
        --output-dir /home/luosx/3dgs/data/drivestudio_nuscenes \
        --scene-name scene-0061
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def get_scene_info(nuscenes_root: Path, scene_name: str) -> dict:
    scenes = json.loads((nuscenes_root / "v1.0-mini" / "scene.json").read_text())
    for s in scenes:
        if s["name"] == scene_name:
            return s
    raise ValueError(f"Scene '{scene_name}' not found in NuScenes mini. "
                     f"Available: {[s['name'] for s in scenes]}")


def verify_structure(nuscenes_root: Path) -> None:
    required = [
        "v1.0-mini/scene.json",
        "v1.0-mini/sample.json",
        "v1.0-mini/sample_data.json",
        "v1.0-mini/calibrated_sensor.json",
        "v1.0-mini/ego_pose.json",
        "v1.0-mini/instance.json",
        "v1.0-mini/sample_annotation.json",
        "samples",
        "sweeps",
    ]
    missing = [r for r in required if not (nuscenes_root / r).exists()]
    if missing:
        raise FileNotFoundError(f"Missing NuScenes files/dirs: {missing}")
    print("✅ NuScenes structure verified")


def create_drivestudio_symlink(nuscenes_root: Path, output_dir: Path) -> None:
    """DriveStudio expects nuscenes data under a specific path structure.
    We create symlinks so DriveStudio can find it without copying 10+ GB.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # DriveStudio NuScenes dataloader looks for:
    #   <data_root>/nuscenes/v1.0-{trainval|mini}/...
    #   <data_root>/nuscenes/samples/...
    #   <data_root>/nuscenes/sweeps/...
    target = output_dir / "nuscenes"
    if target.exists() or target.is_symlink():
        print(f"✅ Symlink already exists: {target}")
        return

    os.symlink(str(nuscenes_root), str(target))
    print(f"✅ Created symlink: {target} -> {nuscenes_root}")


def write_scene_config(output_dir: Path, scene_name: str, scene_token: str) -> Path:
    """Write a DriveStudio scene config YAML for this specific scene."""
    config_dir = output_dir / "configs"
    config_dir.mkdir(exist_ok=True)

    config_path = config_dir / f"{scene_name}.yaml"
    config_content = f"""# DriveStudio OmniRe config for {scene_name}
# Generated by prepare_nuscenes_for_drivestudio.py

data:
  dataset: nuscenes
  scene_idx: {scene_name}
  # NuScenes mini has keyframes at 2Hz; use all available
  start_timestep: 0
  end_timestep: -1
  pixel_source:
    # Use all 6 cameras
    cameras: [0, 1, 2, 3, 4, 5]
    test_image_stride: 0
    downscale_when_loading: 1
    load_sky_mask: true
    load_dynamic_mask: true

# Training settings tuned for RTX 2080 SUPER 8GB
trainer:
  max_steps: 30000
  val_interval: 2000
  log_interval: 200

model:
  background:
    num_gaussians: 400000
  # Enable sky sphere model
  use_sky_model: true
"""
    config_path.write_text(config_content)
    print(f"✅ Scene config written: {config_path}")
    return config_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nuscenes-root", required=True,
                        help="Path to NuScenes root (containing v1.0-mini/, samples/, sweeps/)")
    parser.add_argument("--output-dir", required=True,
                        help="Output directory for DriveStudio data")
    parser.add_argument("--scene-name", default="scene-0061")
    args = parser.parse_args()

    nuscenes_root = Path(args.nuscenes_root)
    output_dir = Path(args.output_dir)
    scene_name = args.scene_name

    print(f"\n[Prepare] NuScenes root : {nuscenes_root}")
    print(f"[Prepare] Output dir   : {output_dir}")
    print(f"[Prepare] Scene        : {scene_name}\n")

    verify_structure(nuscenes_root)

    scene_info = get_scene_info(nuscenes_root, scene_name)
    print(f"✅ Found scene: {scene_info['name']} | token={scene_info['token']}")
    print(f"   Description: {scene_info['description']}")

    create_drivestudio_symlink(nuscenes_root, output_dir)
    write_scene_config(output_dir, scene_name, scene_info["token"])

    print(f"""
╔══════════════════════════════════════════════════════════╗
║  Data preparation complete!                              ║
║                                                          ║
║  Next steps (from a regular terminal):                   ║
║  1. cd /home/luosx/3dgs/drivestudio                      ║
║  2. conda activate drivestudio                           ║
║  3. export PYTHONPATH=$(pwd)                             ║
║  4. bash /home/luosx/3dgs/run_train_omnire.sh            ║
╚══════════════════════════════════════════════════════════╝
""")


if __name__ == "__main__":
    main()
